--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 19-Oct-20 4:33:35 PM
-- Server version: 8.0.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE class_management;

--
-- Drop table `class`
--
DROP TABLE IF EXISTS class;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE class_management;

--
-- Create table `user`
--
CREATE TABLE user (
  id int(11) NOT NULL AUTO_INCREMENT,
  user_name varchar(255) DEFAULT NULL,
  pass_word varchar(255) DEFAULT NULL,
  name varchar(50) DEFAULT NULL,
  email varchar(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `class`
--
CREATE TABLE class (
  msl varchar(50) NOT NULL,
  name varchar(50) DEFAULT NULL,
  gvcn varchar(255) DEFAULT NULL,
  PRIMARY KEY (msl)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'hieupv', '1', 'Hieu pv', 'abc'),
(2, 'anh', '1', 'Anh', 'bcs');

-- 
-- Dumping data for table class
--
INSERT INTO class VALUES
('MSL1', 'Toán Học A', 'Hiêu PV A'),
('MSL2', 'Văn Học a', 'Hiếu'),
('MSL3', 'Toán C', 'Hiếu');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;